### ISSUE TITLE
Bug: unknown response received, spdyn

### ISSUE THREAD

**Issue by Saxfusion** [qdm12/ddns-updater#273]
Running docker compose in host mode with a fixed external dns assignment.

IP updates go through but giving a failure measage anyhow. For the IPv4 as well as the IPv6 record.

For each record i have a corresponding config entry

```json
{
      "provider": "spdyn",
      "domain": "example.spdns.eu",
      "host": "@",
      "user": "my@example.com",
      "password": "MyPwd",
      "token": "my-unique-token",
      "ip_version": "ipv6",
      "provider_ip": false
    },
```

```
Failure (unknown response received: good < correct IP > ), XXmYYs ago
```

in the web UI as well as Container Log

So IP update was ok, just the response code was not handled properly i guess.

Strangely when i log into spdyn.de and look at the host log there i see:

04.12.2021 13:58:43   OK, my-IPv6 (example.spdns.eu)
04.12.2021 13:58:41   OK, my-IPv4 (example.spdns.eu)
04.12.2021 13:58:41   'abuse' Response gesendet (my@example.com)

**Comment by qdm12** [comment]
Thanks for taking the time to report the issue!

It should be fixed in https://github.com/qdm12/ddns-updater/commit/fa15abb781c54253b3404966e60c237be8e9b811

let me know if it happens again after pulling the latest image 😉

**Comment by Saxfusion** [comment]
The update went through i guess.

REPOSITORY            TAG          IMAGE ID       CREATED         SIZE
qmcgaw/ddns-updater   latest       55a20324908d   2 hours ago     19.7MB

The error within the updater disappeared. Strangely the "abuse" message in the spdyn control center is still there together with the ipv4 update, god knows why.

**Comment by qdm12** [comment]
> The update went through i guess.

You can check the commit logged at the beginning of the logs as well, but yeah it should be the latest image :wink: 

> The error within the updater disappeared. 

Nice!

> Strangely the "abuse" message in the spdyn control center is still there together with the ipv4 update, god knows why.

Maybe stop the container for a few hours to see if it makes a difference?

**Comment by Saxfusion** [comment]
Got another one
ERROR unknown response received: nochg < ipv4 or ipv6 >

"nochg" probably means "noch gut" or "still ok, unchanged" since it is the IP on file at the dynDNS service control panel.

**Comment by qdm12** [comment]
Fixed in 01334ad91f20bea6b4b5bdd6043d3fd0b7cfe6fd

Sorry for the delay!

**Comment by Saxfusion** [comment]
No worries, it's your leisure time... 

Would IT Help If in Look Up all published Response Codes that i can find?

I mean they are listed here
https://wiki.securepoint.de/SPDyn/R%C3%BCckgabecodes
Just If you need Input regarding translation.


Still having this on the Site with the Adguard DNS Setup.
Need to check the log, when I find the time, as to why he thinks it needs an update if it is unchanged every 1-3hrs.

**Comment by qdm12** [comment]
Yes there were already incorporated in the code even before this issue got created :wink: 

https://github.com/qdm12/ddns-updater/blob/ae7f10448da8716edb47a3535896f35d003c9cd6/internal/settings/providers/spdyn/provider.go#L152-L164

However they don't precise in their docs they return the IP address next to `nochg 1.2.3.4` and `good 1.2.3.4` so the program wasn't expecting those responses. It would just expect `nochg` or `good`. Now they're both changed to check the prefixes only. I guess for once it's on them their docs is not accurate :smile_cat: 

> as to why he thinks it needs an update if it is unchanged every 1-3hrs.

Yes feel free to create another issue if it's unrelated to the unknown response. Thanks!
