### ISSUE TITLE
IP method ddnss6 is only for IPv6 addresses

### ISSUE THREAD

**Issue by tools400** [qdm12/ddns-updater#50]
Hi, am I correct, that ddns-update cannot update IPV6 addresses for Cloudflare?

The following piece of code implies that, along with the error that I mentioned in the subject area of this issue:

`
		cloudflarePutBody{
			Type:    "A",
			Name:    host,
			Content: ip.String(),
			Proxied: proxied,
			TTL:     ttl,
		},
`
Regards,
Thomas.

**Comment by qdm12** [comment]
Yes for now it can only update AAAA records for some other providers (DDNSS.de, Infomaniak, etc.). I need to add support for Ipv6 so let's keep this issue opened, I'll close it once IPv6 records are supported.

**Comment by tools400** [comment]
That was truly a fast response. Thanks.
I am looking forward to your IPV6 support.

**Comment by qdm12** [comment]
Hello, I added support for ipv6 and AAAA now for Cloudflare, can you please try it? (I don't have ipv6 nor cloudflare ha!)

The image is `qmcgaw/ddns-updater:cloudflare-ipv6`, PR is [here](https://github.com/qdm12/ddns-updater/pull/71) and newer documentation is [here](https://github.com/qdm12/ddns-updater/tree/cloudflare-ipv6) (essentially you can remove `identifier` from your settings, and you can specify `"ip_version": "ipv6"` - if you don't it will update ipv4 or ipv6). You can also add another record with the same exact settings but change the `"ip_version": "ipv4"` if you want to update the A and AAAA records at the same time.

**Comment by qdm12** [comment]
Actually i had to merge it in the master branch, so it's now available in the `:latest` docker tag. I'll close the issue, feel free to comment / reopen if it doesn't work (or if it works). Thanks!

**Comment by tools400** [comment]
I promise to check the new ipv6 support for Cloudflare as soon as possible. But it may take until next weekend.

**Comment by qdm12** [comment]
Hi, Thanks for pinging back! No hurry, anyway someone will eventually create another issue if ipv6 doesn't work :smile: Of course if you can find a use for it, great :+1: !

**Comment by tools400** [comment]
Hi, I cannot make it work with the following config file:

```
{
    "settings": [
        {
            "provider": "cloudflare",
            "zone_identifier": "1b...e0",
            "domain": "tools400.me",
            "host": "testing",
            "ttl": 1,
            "token": "8o...IW",
            "ip_version": "ipv4"
        }
    ]
}
```

The error message I get is:

```
💸  Help me? https://github.com/sponsors/qdm12
2020-06-06T09:25:23.998Z        WARN    IP method "" is not recognized for settings {"domain":"tools400.me","host":"testing","provider":"cloudflare"}      {"node_id": 0}
2020-06-06T09:25:23.998Z        ERROR   no settings found in config.json        {"node_id": 0}
```

The web UI is also not available at port 8000.

What did I miss? Any ideas?

**Comment by qdm12** [comment]
I think this is an old Docker image, try pulling it again?

**Comment by tools400** [comment]
I pulled the docker image again and I am a little step further. The ddns-updater successfully updated the ipv4 address, but could not figure out my public ipv6 address:

```
2020-06-06T15:26:36.116Z        INFO    Found 2 settings to update records
2020-06-06T15:26:36.448Z        INFO    Reading history from database: domain tools400.me host @
2020-06-06T15:26:36.448Z        INFO    Reading history from database: domain tools400.me host @
2020-06-06T15:26:36.449Z        INFO    Web UI listening at address 0.0.0.0:8000 with root URL ""
2020-06-06T15:26:36.449Z        INFO    backup: disabled
2020-06-06T15:26:37.426Z        ERROR   no public ipv6 address found
2020-06-06T15:26:37.432Z        INFO    IPv4 address of tools400.me is 104.24.114.72 and your IPv4 address is 89.244.226.38
2020-06-06T15:26:37.434Z        INFO    Updating record [domain: tools400.me | host: @ | provider: cloudflare | ip: ipv4] to use 89.244.226.38
```

My Fritz!Box does have a public ipv6 address, as well as my Synology NAS running Docker has a ipv6 address. All `IP_METHOD*` environment variables (3) are set to the default value `cycle`.

**Comment by qdm12** [comment]
There is no OS in the container so no shell 😕 

Can you try

```sh
docker run -it --rm alpine:3.11 wget -qO- https://ip6.ddnss.de/meineip.php
```

If it doesn't work, please try:

```sh
docker run -it --rm --sysctl net.ipv6.conf.all.disable_ipv6=0 alpine:3.11 wget -qO- https://ip6.ddnss.de/meineip.php
```

If the second works but not the first command, please read [that section](https://github.com/qdm12/private-internet-access-docker/wiki/Common-issues#ipv6-does-not-work) (for another of my container, but I'll add it there if that's the cause).

Adding this to your ddns-updater run command / docker-compose should fix your problem 😉

**Comment by tools400** [comment]
Both commands timed out, although your container is assigned to network 'bridge', which has ipv6 enabled. I think I first ask my son to help me before stealing your time.

**Comment by qdm12** [comment]
No problem, I'm happy to help (and fix that container too!).
Sadly I have no ipv6 from my isp, so I can't test it 😞 

On my side, running

```sh
docker run -it --rm alpine:3.11 wget -qO- https://ip6.ddnss.de/meineip.php
```

gives me `wget: can't connect to remote host: Address not available` and

```sh
docker run -it --rm --sysctl net.ipv6.conf.all.disable_ipv6=0 alpine:3.11 wget -qO- https://ip6.ddnss.de/meineip.php
```

gives me `wget: can't connect to remote host: Network unreachable`. What do you get?

And out of curiosity, does [https://api6.ipify.org](https://api6.ipify.org) work and give you your ipv6 address? Thanks!

**Comment by tools400** [comment]
Hi,

Good news. I changed `network_mode` from `bridge` to `host` in `docker-compose.yaml` and now it works fine. I could successfully update a 'A' and a 'AAAA' record at Cloudflare. So basically updating 'AAAA' records at Cloudflare works. Now I have to check my IPv6 configuration.

Last but not least, I also successfully tested specifying multiple host as a comma separated list at parameter "host". Nice and useful feature. I like it.

Good job. Thank you very much.

Regards,

Thomas.

**Comment by tools400** [comment]
> And out of curiosity, does https://api6.ipify.org work and give you your ipv6 address? Thanks!

That also timed out when executed in a docker container. But it returned the proper address when executed in a browser. So that is the same thing as with https://ip6.ddnss.de/meineip.php.

I need to check and re-configure my IPv6 configuration.

Thomas.

**Comment by qdm12** [comment]
Glad to hear!

Let me know once you fix it with your Docker bridged network, I'll add it to the readme. 

Congrats for switching to ipv6 :+1:

**Comment by tools400** [comment]
I will gladly get in touch with you, once that I fixed the ipv6 problem. But be patient. It may take some days.

**Comment by hereisderek** [comment]
I have ipv6 enabled, and I'd love to help, however, my knowledge regarding docker is rather limited

alpine:latest doesn't seem to have ipv6 enabled by default, which is probably why we weren't able to get the ipv6 address 

```
derek /srv/docker docker run -it --rm alpine:latest ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:07
          inet addr:172.17.0.7  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:90 (90.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


 derek /srv/docker docker run -dit --name alpine1 alpine ash
1cf868d0e7108c9c40efb56eade5aeff3a007bf4651daa084142db706591087d

derek /srv/docker docker container ls
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                  PORTS                                                        NAMES
1cf868d0e710        alpine                                 "ash"                    25 seconds ago      Up 6 seconds                                                                         alpine1

derek /srv/docker docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "c3b1d450912059ef7abf23f1e3aa103342bc75a0ae7f8b6534544eb54dea6cb4",
        "Created": "2020-11-18T15:20:39.259325364+13:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1cf868d0e7108c9c40efb56eade5aeff3a007bf4651daa084142db706591087d": {
                "Name": "alpine1",
                "EndpointID": "91a8dedf2207bb206c5ecd41e918bbf41256109bd89aa1c58274f3a8475678f6",
                "MacAddress": "02:42:ac:11:00:07",
                "IPv4Address": "172.17.0.7/16",
                "IPv6Address": ""
            }
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**Comment by hereisderek** [comment]
also found some links that might be useful for future reference
https://docs.docker.com/network/network-tutorial-standalone/
https://docs.docker.com/network/bridge/#use-ipv6

**Comment by hereisderek** [comment]
1. update /etc/docker/daemon.json 

```
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}
```

2. system restart docker

3. check `docker network inspect bridge` "EnableIPv6": true

4. change docker-compose.yml to `network_mode: host`

5. my config.json is as follow, those two entries are actually the same domain, not sure how to update both ipv4 and ipv6 at the same time

```
{
    "settings": [
        {
            "provider": "cloudflare",
            "domain": "mydomain.come",
            "zone_identifier": "fake-id-xxx",
            "host": "@",
            "token": "fake-token-xxx",
            "ttl": 1,
            "ip_version": "ipv4",
            "no_dns_lookup": true
        },
        {
            "provider": "cloudflare",
            "domain": "mydomain.come",
            "zone_identifier": "fake-id-xxx",
            "host": "@",
            "token": "fake-token-xxx",
            "ttl": 1,
            "ip_version": "ipv6",
            "no_dns_lookup": true
        },
    ]
}
```

problem, the ipv6 address is actually still wrong

**Comment by qdm12** [comment]
Thanks @hereisderek I'll add what you wrote to the wiki!

> not sure how to update both ipv4 and ipv6 at the same time

You cannot for now but that's a nice feature that I should add (like option `ipv4 and ipv6` on top of `ipv4`, `ipv6` and `ipv4 or ipv6`)

> the ipv6 address it detected is actually wrong

I just fixed the links in the readme for noip, although the ones in the code were correct.

Do you get the correct IPv6 address using http://ip1.dynupdate6.no-ip.com and http://ip1.dynupdate6.no-ip.com:8245? Also can you access them over https? Thanks!

**Comment by hereisderek** [comment]
sorry I completely missed your reply, here is my testing results:

![image](https://user-images.githubusercontent.com/839795/104389430-4ecb3280-55a0-11eb-9de8-6202c0313c07.png)

`the ipv6 address it detected is actually wrong,`

I can't remember exactly, but it might be that the ipv6 address that was returned from the URL are correct, but somehow it was parsed wrong in the app. but again, I don't remember exactly

**Comment by qdm12** [comment]
That is very much likely related to the issue #210.

Maybe using the new environment variable `IPV6_PREFIX` can help.

**Comment by qdm12** [comment]
This should be solved in 954dffd3a78751061c01e0f9135086a306f57dc2 for the latest image and future release v2.6.0 (it was a bad ipv6 regex).

Closing this, feel free to open another issue if you still encounter ipv6 issues with cloudflare or other providers.
