### ISSUE TITLE
Feature request: add dynv6 provider?

### ISSUE THREAD

**Issue by lukaschan** [qdm12/ddns-updater#89]
What's the feature?
Would "dynv6" to be included as a provider?
https://dynv6.com/

Why do you need this feature?
Would provide potential to expand your service of providers?

Extra information?
Thanks!

**Comment by qdm12** [comment]
Hey sorry for the very long delay! I'm on it now!

There is an experimental version using the Docker image `qmcgaw/ddns-updater:dynv6` which should work, together with the documentation [here](https://github.com/qdm12/ddns-updater/blob/dynv6/docs/dynv6.md).

A few additional questions for you:

- Can you have wildcards records with it?
- Can you please give me the output from the following commands, replacing the values accordingly (such as `youractualtoken`):

```sh
# 1
docker run --rm alpine:3.12 wget -SO- "https://ipv4.dynv6.com/api/update?zone=yourdomain.com&ipv4=yourip&token=youractualtoken"
# 2
docker run --rm alpine:3.12 wget -SO- "https://ipv4.dynv6.com/api/update?zone=somedomainyoudontown.com&ipv4=127.0.0.1&token=youractualtoken"
# 3
docker run --rm alpine:3.12 wget -SO- "https://ipv4.dynv6.com/api/update?zone=somedomainyoudontown.com&ipv4=127.0.0.1&token=youractualtoken"
# 4
docker run --rm alpine:3.12 wget -SO- "https://ipv4.dynv6.com/api/update?zone=youdomain.com&ipv4=somegarbage&token=youractualtoken"
```

Thanks!

**Comment by lukaschan** [comment]
<img width="1286" alt="Screen Shot 2020-12-26 at 9 07 10 PM" src="https://user-images.githubusercontent.com/3959525/103152008-5d52d500-47be-11eb-9fb1-eace4f83c000.png">

Thanks for your attention!

With your guide above, I set it up in may QNAP NAS, but an error occurred...

Pl. look into it?

PS: I know little about coding stuff... Maybe I just can't set it up properly :(

**Comment by qdm12** [comment]
Thanks for getting back to me. I fixed the problem, can you try re-pulling and try again?

Also can you try the commands above so I can cover all cases in the program? To run these, you can either:

- connect to your NAS over SSH
- In the QNAP UI there is most likely a terminal app
- Install Docker Desktop on your computer (compatible with Windows and OSX) and run them with cmd for example

Thanks!

**Comment by lukaschan** [comment]
<img width="556" alt="Screen Shot 2020-12-27 at 10 45 40 AM" src="https://user-images.githubusercontent.com/3959525/103162854-e145a500-4830-11eb-871c-7e85af1f578e.png">

Thanks again! But there is still an error "token cannot be empty".
